name: Build for Windows

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sdkman/sdkman-action@master
      id: sdkman
      with:
        candidate: java
        version: 24.0.1-graal
    - uses: actions/setup-java@v1
      id: setup-java
      with:
        java-version: 24
        jdkFile: ${{ steps.sdkman.outputs.file }}
    - name: Setup GRAALVM_HOME
      run: set GRAALVM_HOME=$JAVA_HOME
    - name: Make staging directory
      run: mkdir staging
    - name: Build JAR with Maven
      run: mvn -B install
